SELECT
    `COLUMNS`.COLUMN_NAME AS `列名`,
    `COLUMNS`.DATA_TYPE AS `字段类型`,
    `COLUMNS`.CHARACTER_MAXIMUM_LENGTH AS `长度`,
    `COLUMNS`.IS_NULLABLE AS `是否为空`,
    `COLUMNS`.COLUMN_DEFAULT AS `默认值`,
    `COLUMNS`.COLUMN_COMMENT AS `备注`
FROM
    information_schema.`COLUMNS`
WHERE
        `COLUMNS`.TABLE_SCHEMA = ?
  AND `COLUMNS`.TABLE_NAME = ?